### ISSUE TITLE
Automating the brick oven in MC 1.7.10

### ISSUE THREAD

**Issue by wizard1399** [einsteinsci/betterbeginnings#125]
I have a concern I wanted to bring to your attention. I was wondering how automation is handled concerning the oven. Is there a means to lock a recipe in the oven so that items can be piped in?

For example, assume an HQM task requires 100 cakes and 100 pumpkin pies. Is there a way to tell the oven to use the 3 wheat it just recieved to craft as part of cake recipe and not to cook bread? Perhaps a button to toggle between crafting mode and cooking mode would help here. In crafting mode, players could designate a recipe by placing ghost items in the crafting grid and pull items from an input storage.

**Comment by Leviathan143** [comment]
It's currently not automateable at all, the input slots aren't accessible.

**Comment by einsteinsci** [comment]
Unfortunately, due to the fact that the brick oven has a crafting grid for inputs, it's only as automatable as the vanilla crafting table: not automatable at all. Since the 1.7.10 branch is at its nearly-final version, I will not be adding this there. However, this would make a valuable addition as an upcoming feature for 1.1.0 (on the 1.8.X / 1.9.X branches), along with a form of automation for the crafting table.

**Comment by einsteinsci** [comment]
Since this is a requested feature, I will close this as an issue. You can see progress on this upcoming feature on the [Trello board](https://trello.com/c/5VfhQXuX)
