### ISSUE TITLE
[Suggestion] In-game documentation

### ISSUE THREAD

**Issue by POKFX45** [einsteinsci/betterbeginnings#149]
Hi, i really like your mod, but the fact that every so often i need to read the wiki it's really boring, so would be great if you add in-game documentation 👍

**Comment by Leviathan143** [comment]
This repo is dead. DO NOT CREATE ISSUES HERE. The new repo is Leviathan143/betterbeginnings-modified. Please close this issue and recreate it there.

#147 is clearly visible on the issues page. It explains that this repo is dead, why it's dead and links to the new repo. I do not watch this repo, I only noticed this issue by chance.

Sorry if I sounded rude. I thought I'd fixed all of BB's issues, only to find that the dead repo had 7 issues on it, despite me doing my best to notify people that this repo is dead.

Also there are in-game docs. The JEI description page provides an overview of every block or item that needs explanation.

**Comment by einsteinsci** [comment]
Re-opening this issue as it is certainly necessary in the upcoming redesign.

**Comment by MagmaBro123** [comment]
You have 5 issues. Please read them. If this mod is dead, please remove it.

**Comment by Daomephsta** [comment]
Don't co-opt an existing issue for an unrelated issue! Make your own issue. 
It's a pain for authors and users to find existing discussion otherwise.

As for your question, see #163

**Comment by einsteinsci** [comment]
> @MagmaBro123 : You have 5 issues. Please read them. If this mod is dead, please remove it.

First off, this is the first time I've seen activity and notifications on this project in more than a few years.

I dropped this project for unexpected IRL reasons at the time, paired up with a lot of burnout from the mod. I never picked it up after recovering due to a loss of interest, the modding scene moving way faster than I could adapt, and general disinterest in the mod's goals.

I don't plan on continuing development.

The project was always a mess, with some truly terrible object-oriented design. This style of gameplay was never something I particularly cared for, so I had little stake outside of development. I never used it in any of my own modded playthroughs. Daomephsta (aka iLiminate) has long since moved on as well. This project is effectively dead.

Most importantly though, this is an open-source project, licensed under GPL v3. If ***you*** want to continue development, fix bugs, compatibility issues, terrible design decisions, you are perfectly able to do so yourself. **You don't need to ask permission.** It's already given in the license. Just clone the repo and start working with the code, and follow the license if you decide to release.

That is the whole reason this project was never "removed"; that's pointless. I don't delete old work that could potentially be useful to someone else. Even if my work sucks. That's not how open-source works. *If you want to try to pick up the pieces, nothing I'm doing is stopping you.* That's the whole reason the project is licensed the way it is.

Or you can keep complaining that a dead project is dead.

I'll try to put up one last commit for the readme and mark it archived to freeze this issue tracker. The code will remain, if anyone wants to continue development; I see no reason to "remove" it. If anyone wants to fork it, they still can.
