### ISSUE TITLE
(If there is anyone alive) AdvancedCrafting.removeRecipe not working in CraftTweaker when trying to remove armor craft

### ISSUE THREAD

**Issue by kotmatross28729** [einsteinsci/betterbeginnings#162]
Title, I tried to understand how the crafttweaker support works here, and somehow I managed to write some part of the script (remove the crafting of the diamond sword, knife, and add support to (so far) swords from the Thermal Foundation, but when I try to remove the diamond armor recipe from the mod , I get either an error or the recipe is not deleted

this is what my script looks like: https://pastebin.com/zWMQ0KHm

the line that should remove the leggings recipe is commented because it throws a java.lang.ArrayIndexOutOfBoundsException: 4 error, and points exactly to line 4, it doesn't matter, even if it's empty or doesn't exist.
Here is an excerpt from the minetweaker (crafttweaker) log: https://pastebin.com/ddVhpXvZ

P.S: as soon as i noticed it happens with all armor.
my only guess (why the recipes aren't being deleted) is the wool OreDictionary.
Although I may not understand this, but in https://github.com/einsteinsci/betterbeginnings/blob/main/src/main/java/net/einsteinsci/betterbeginnings/register/RegisterRecipes.java
"Blocks.wool OreDictionary.WILDCARD_VALUE" is used, and my script uses <ore:blockCloth>, but it's probably the same thing, I don't know, like the error with deleting the leggings recipe

And, as I understand this repo is dead, so it's quite sad that such a good mod is no longer maintained, I hope that someday someone will make a similar mod for 1.7.10

**Comment by MagmaBro123** [comment]
I doubt anyone cares about this mod. Twilight Forest also has some issues with it.

**Comment by Daomephsta** [comment]
This mod is unmaintained (see #163), but I've taken a look at the source to see if I can figure out what's happening.
Not much luck unfortunately, and setting up a 1.7.10 dev env to take a look is a lot more work than it used to be. 

However the issue should be avoided if you use `removeOutput` instead of `removeRecipe`. 
Why are you using `removeRecipe`?
 That's only necessary when there are multiple recipes with the same output, and you want to remove only some of them. Otherwise `removeOutput` is easier to use and slightly faster as only has to match the output against all recipes; rather than the output, inputs, and catalysts.

**Comment by kotmatross28729** [comment]
Oh, thank you very much, I guess I didn't quite read the wiki, I'm used to writing something like recipes.addShaped and recipes.remove, they work on the same principle, i.e. (<modid:itemid>). Thanks again!
