### ISSUE TITLE
Make campfire not so pointless

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#47]

**Comment by einsteinsci** [comment]
Anon just came up with a few brilliant ideas. Here's a link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2192122-betterbeginnings-mod?comment=220

**Comment by gogoghouha** [comment]
Bug: if an item/block (no matter which one) is placed instead of a pan, raw food will be cooked into cooked food, not into charred meat.

**Comment by einsteinsci** [comment]
Looks like I'll need to make that slot only accept ItemPan, and then only fully cook the food if the slot contains an ItemPan, instead of not null.

**Comment by dizzysoul** [comment]
> Bug: if an item/block (no matter which one) is placed instead of a pan, raw food will be cooked into cooked food, not into charred meat.

This bug has actually been a godsend for me to help make the campfire more relevant in my modpack, since I wanted to use it as a means of cooking food before players obtain a pickaxe.

I think that if/when you decide to fix this bug, you should also allow players to use sticks (as a spit) for cooking basic things, and remove cobblestone from the recipe, so the campfire can be used before the "pickaxe" stage of progression.

**Comment by einsteinsci** [comment]
Pretty sure this one has been done for a while.
